# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Minkura' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Minkura

platform :ios, '7.0'

pod 'PayPal-iOS-SDK/Core'


  target 'MinkuraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MinkuraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
